name: Publish Docker Image

on:
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unum/ukv:0.3.0-focal
      
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}
      
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/ukv
